# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference
version: 2
updates:
  - package-ecosystem: "github-actions"
    directories: 
      - "/" # Default .github/workflows directory for this repo's workflows
      - "/src" # Reusable workflows directory
    schedule:
      interval: "weekly"
    labels:
      - "type: chore"
      - "work: obvious"
      - "effort: 1"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "type: chore"
      - "work: obvious"
      - "effort: 1"