name: Check Tasks

permissions: {}
on:
    pull_request:
        types: [opened, edited]

jobs:
  check-tasks:
    name: Check Tasks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.11"
      - name: Check for open tasks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_COMMIT_SHA: ${{ github.event.pull_request.head.sha}}
          GITHUB_COMMENT: ${{ github.event.comment.body }}
        run: python src/check_tasks.py
