name: PR Review

permissions: {}
on:
  issue_comment:
    types: [created, edited]

jobs:
  review:
    name: AI Code Review
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    # Only if the comment contains the trigger word "ood ai review"
    # if: contains(github.event.comment.body, 'ood ai review')
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install openai requests

      - name: Run AI Review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_COMMIT_SHA: ${{ github.event.pull_request.head.sha}}
          GITHUB_COMMENT: ${{ github.event.comment.body }}
        run: python src/code_review.py
