name: Create Release
permissions: {}
on:
  workflow_call:
    inputs:
      draft:
        description: "Create the release as a draft"
        type: boolean
        default: true
  push:
    branches:
      - main
      - beta
      - dev
      - staging
jobs:
  detect:
    permissions:
      contents: read
    uses: ./.github/workflows/detect-new-changelog-version.yml
  publish-called:
    needs: detect
    if: github.event_name == 'workflow_call' && needs.detect.outputs.should-release == 'true'
    permissions:
      contents: write
    uses: ./.github/workflows/publish-release.yml
    with:
      version: ${{ needs.detect.outputs.new-version }}
      prerelease: ${{ needs.detect.outputs.is-prerelease == 'true' }}
      release-notes: ${{ needs.detect.outputs.release-notes }}
      draft: ${{ inputs.draft }}
  publish-pushed:
    needs: detect
    if: github.event_name != 'workflow_call' && needs.detect.outputs.should-release == 'true'
    permissions:
      contents: write
    uses: ./.github/workflows/publish-release.yml
    with:
      version: ${{ needs.detect.outputs.new-version }}
      prerelease: ${{ needs.detect.outputs.is-prerelease == 'true' }}
      release-notes: ${{ needs.detect.outputs.release-notes }}
      draft: true
